### ISSUE TITLE
`ananc new` does not work on my system

### ISSUE THREAD

**Issue by ColonelPhantom** [saru-tora/anansi#1]
On my system, trying to use `ananc new` gives an error, which seems to be because `ananc` tries to open its own binary based on `argv[0]`. However, `argv[0]` (for me) does not refer to a path, it is simply `ananc`. Trying to open this errors because it is actually located in `~/.cargo/bin/ananc`.

I can work around this by using `$(which ananc) new` instead, but it would be nice if this could be fixed.

By the way, congratulations on creating Anansi! I haven't used it at all yet but look forward to playing with it :smile:

**Comment by saru-tora** [comment]
Thanks for the feedback. Hopefully, it should be fixed now!
