### ISSUE TITLE
Hello)

### ISSUE THREAD

**Issue by kalinavladd** [saru-tora/anansi#21]
hi, i'm a junior django developer (1 year experience) and i see django inspiration in your code. I have been practicing rust for 4 months and wanted to be involved in the development. I know that writing a framework is not an easy task, but I could do assignments that fit the experience))) If you don't mind, please answer me

**Comment by saru-tora** [comment]
Thank you for the interest, but unfortunately, the API is probably still too unstable for code contributions.
