### ISSUE TITLE
[docs] `ananc app` no longer creates `base.rs.html`

### ISSUE THREAD

**Issue by aleksa-stajcic** [saru-tora/anansi#3]
Following the tutorial and I discovered that the `ananc app forum` command didn't create a `base.rs.html` file. I'm assuming the views are now created through the `ananc make-view` command and that this was overlooked in the documentation and wasn't removed.
![image](https://user-images.githubusercontent.com/49615937/195982287-1ee19d4f-5d58-46e8-9a4e-5179279def24.png)

**Comment by saru-tora** [comment]
You're right. Should be fixed now.
